exclude: ["ReadMe.md", "License.md"]

title : Machine learning notes
author :
  name : Leonardo Espin
  github : leoespin

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 0
  show_warnings     : false
